In [65]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import cv2

import matplotlib
#matplotlib.use('TkAgg')
#%matplotlib
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import scipy
import scipy.io as sio
from sklearn.metrics import mean_squared_error 
from scipy.spatial.distance import cdist
import random 
from utils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [74]:
points_2d_pic_a = np.loadtxt('../data/pts2d-pic_a.txt')
points_2d_pic_b = np.loadtxt('../data/pts2d-pic_b.txt')
img_left = load_image('../data/pic_a.jpg')
img_right = load_image('../data/pic_b.jpg')

print(points_2d_pic_a)
print("")
print(points_2d_pic_b)

[[880. 214.]
 [ 43. 203.]
 [270. 197.]
 [886. 347.]
 [745. 302.]
 [943. 128.]
 [476. 590.]
 [419. 214.]
 [317. 335.]
 [783. 521.]
 [235. 427.]
 [665. 429.]
 [655. 362.]
 [427. 333.]
 [412. 415.]
 [746. 351.]
 [434. 415.]
 [525. 234.]
 [716. 308.]
 [602. 187.]]

[[ 731.  238.]
 [  22.  248.]
 [ 204.  230.]
 [ 903.  342.]
 [ 635.  316.]
 [ 867.  177.]
 [ 958.  572.]
 [ 328.  244.]
 [ 426.  386.]
 [1064.  470.]
 [ 480.  495.]
 [ 964.  419.]
 [ 695.  374.]
 [ 505.  372.]
 [ 645.  452.]
 [ 692.  359.]
 [ 712.  444.]
 [ 465.  263.]
 [ 591.  324.]
 [ 447.  213.]]


In [93]:
A = np.zeros([len(points_2d_pic_a), 9])
for i in range(len(points_2d_pic_a)):
    A[i][0] = points_2d_pic_a[i][0] * points_2d_pic_b[i][0]
    A[i][1] = points_2d_pic_a[i][0] * points_2d_pic_b[i][1]
    A[i][2] = points_2d_pic_a[i][0]
    A[i][3] = points_2d_pic_a[i][1] * points_2d_pic_b[i][0]
    A[i][4] = points_2d_pic_a[i][1] * points_2d_pic_b[i][1]
    A[i][5] = points_2d_pic_a[i][1]
    A[i][6] = points_2d_pic_b[i][0]
    A[i][7] = points_2d_pic_b[i][1]
    A[i][8] = 1

U, S, V = np.linalg.svd(A)

M = V[-1:9]
M = np.reshape(M, (3,3))

U1, S1, V1 = np.linalg.svd(M)
S1[2] = 0
F = U1.dot(np.diag(S1).dot(V1))
F = F / np.max(F) #F[2, 2]
print(F)

[[-5.36532415e-07  8.83981093e-06 -9.07836099e-04]
 [ 7.90760078e-06  1.21382365e-06 -2.64366809e-02]
 [-1.88694534e-03  1.72419095e-02  1.00000000e+00]]


In [101]:
this = 0.05

this2 = 119

if(np.absolute(this2) < this):
    print(this2)